/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e68a97119703c50bc67c2a3
*
* You will get 10% discount for each one of your friends
* 
*/
package com.wylfrandtest.config;

import static springfox.documentation.builders.PathSelectors.regex;

import java.io.UnsupportedEncodingException;
import java.util.Date;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

import com.auth0.jwt.JWT;
import com.auth0.jwt.algorithms.Algorithm;
import com.google.gson.Gson;
import com.wylfrandtest.db.wylfrandtest_db.entity.User;

import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger.web.ApiKeyVehicle;
import springfox.documentation.swagger.web.SecurityConfiguration;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@Configuration
@EnableSwagger2
@Profile({"DEV"})
public class SwaggerConfiguration {
    
	@Value( "${token.secret}" )
	private String secret;
	
	@Bean
	public Docket productApi() {
		return new Docket(DocumentationType.SWAGGER_2).select()
				.apis(RequestHandlerSelectors.basePackage("com.wylfrandtest.controller"))
				.paths(regex("/.*")).build();

	}


	@Bean
    SecurityConfiguration security() throws IllegalArgumentException, UnsupportedEncodingException {

	    User user = new User();
	    user.setUsername("admin");
	    user.setPassword("62f264d7ad826f02a8af714c0a54b197935b717656b80461686d450f7b3abde4c553541515de2052b9af70f710f0cd8a1a2d3f4d60aa72608d71a63a9a93c0f5");
	    
		Algorithm algorithm;
		Gson gson = new Gson();
		algorithm = Algorithm.HMAC256(secret);
		Date date = new Date();
		long t = date.getTime();
		Date expirationTime = new Date(t + 28800000l);
		String token = JWT.create().withSubject(gson.toJson(user )).withExpiresAt(expirationTime)
	    .withClaim("user",gson.toJson(user))
	    .sign(algorithm);    	
	    
        return new SecurityConfiguration("","","","","Bearer " + token ,ApiKeyVehicle.HEADER,"Authorization","");
    }
    
}
